"""Python entry point for the optlib C++ extension."""

from __future__ import annotations

from ._optlib import (
    Add,
    Axpy,
    DifferentiationScheme,
    Dot,
    FirstOrderMethod,
    Gemm,
    Gemv,
    LearningRateSchedule,
    LearningRateAt,
    LineSearchMethod,
    Minimize,
    MinimizeSecondOrder,
    MinimizeRosenbrock,
    MinimizeRosenbrockSecondOrder,
    MinimizeRosenbrockZeroOrder,
    MinimizeZeroOrder,
    Norm2,
    NormInf,
    NumericGradient,
    RosenbrockAutogradGradient,
    RosenbrockGradient,
    RosenbrockGradientAutograd,
    RosenbrockGradientNumeric,
    RosenbrockHessian,
    RosenbrockNumericalGradient,
    RosenbrockValue,
    SecondOrderMethod,
    Version,
    ZeroOrderMethod,
)

__version__ = Version()
__all__ = [
    "Add",
    "Axpy",
    "DifferentiationScheme",
    "Dot",
    "FirstOrderMethod",
    "Gemm",
    "Gemv",
    "LearningRateSchedule",
    "LearningRateAt",
    "LineSearchMethod",
    "Minimize",
    "MinimizeSecondOrder",
    "MinimizeRosenbrock",
    "MinimizeRosenbrockSecondOrder",
    "MinimizeRosenbrockZeroOrder",
    "MinimizeZeroOrder",
    "Norm2",
    "NormInf",
    "NumericGradient",
    "RosenbrockAutogradGradient",
    "RosenbrockGradient",
    "RosenbrockGradientAutograd",
    "RosenbrockGradientNumeric",
    "RosenbrockHessian",
    "RosenbrockNumericalGradient",
    "RosenbrockValue",
    "SecondOrderMethod",
    "Version",
    "ZeroOrderMethod",
    "__version__",
]
